name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v1

      - name: terraform init
        uses: docker://hashicorp/terraform:latest
        with:
          entrypoint: terraform
          args: init

      - name: terraform validate
        uses: docker://hashicorp/terraform:latest
        with:
          entrypoint: terraform
          args: validate